scripts/create_burndown.py
There was a bug where the lines for story points and tasks under the water
line were not printed correctly and trollolo crashed. This commit fixes those
issues.
=> Fixed handling of extra tasks and story points

.gitignore
When you have working directory pointed to root of the repo - that is very
convenient
=> Git ignore yaml and png files in the root of a repo

README.md, lib/cli.rb, lib/settings.rb, man/trollolo.1.md, spec/data/trollolorc_with_board_aliases, spec/unit/cli_spec.rb, spec/unit/settings_spec.rb
With board aliases defined in `trollolorc` file, the users will be able to use "easy" names instead of actual ids for the various commands (for --board-id option).
=> Use board aliases

Gemfile, spec/unit/spec_helper.rb
Version 1.0 of codeclimate test reporter introduced changes that
break configurations for older versions and thus requires some
adoptations.
In addition this enforces codeclimate-test-reporter version >= 1.0.0.
https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md#upgrading-from-pre-10-versions
====
$ bundle exec rspec
W, [2016-11-23T19:38:05.467313 #5382]  WARN -- :       This usage of the Code Climate Test Reporter is now deprecated. Since version
1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
run the provided `codeclimate-test-reporter` binary separately to report your
results to Code Climate.
More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md
=> Adopt to changes of codeclimate-test-reporter gem

lib/burndown_chart.rb, lib/cli.rb, spec/unit/burndown_chart_spec.rb
Allow to specify the `total_days` and `weekend_lines` variables when running `trollolo burndown --new-sprint`. :bowtie: 
Closes https://github.com/openSUSE/trollolo/issues/77
=> Add total days and weekend lines as params

CHANGELOG.md, lib/version.rb
- Add in `trollolo burndown --new-sprint` comand the `total_days` and `weekend_lines` params. Closes #77.
- Change stdout output when running set-priorities to render the new priority instead of the old one. Fixes #72.
=> Prepare version 0.0.11

CHANGELOG.md, lib/scrum/sprint_board.rb, lib/scrum/sprint_cleaner.rb
Find cards labeled 'Unplanned' and remove the label when moving
them from the sprint board to the planning board.
=> Remove 'Unplanned' label on `cleanup-sprint`

CHANGELOG.md, lib/backup.rb, lib/burndown_chart.rb
Include "require 'fileutils'" in the files that call the FileUtils module.
=> Fix missing 'require' for FileUtils

CHANGELOG.md, trollolo.gemspec
It is not working and this allow us to remove the activesupport  dependency.
Closes https://github.com/openSUSE/trollolo/issues/96.
=> Remove Ruby 2.1 support

CHANGELOG.md, lib/version.rb
- Find and remove 'Unplanned' labels on `cleanup-sprint`. Fixes #72.
- Fix `trollolo burndown-init` and `trollolo backup`.
- Remove Ruby 2.1 support. Closes #96.
=> Prepare version 0.0.12

Gemfile
To avoid that it automatically updates to the last one and Travis fails. :bowtie:
=> Set Rubocop version

CHANGELOG.md, man/trollolo.1.md
Add documentation for all available CLI commands to the manpage.
Fix https://github.com/openSUSE/trollolo/issues/83.
=> Add documentation for CLI commands

CHANGELOG.md, Gemfile, lib/scrum/sprint_cleaner.rb, spec/data/vcr/sprint_cleanup.yml, spec/unit/scrum/sprint_cleaner_spec.rb
Add automatic generation of burndown data when calling
`trollolo cleanup-sprint`. This assumes the burndown-data-*.yaml is in
the current working directory. The user gets notified if new data was
generated or not.
Fix https://github.com/openSUSE/trollolo/issues/68.
=> Run burndown generation on `cleanup-sprint`

CHANGELOG.md, README.md, lib/scrum/backlog_mover.rb, spec/unit/scrum/backlog_mover_spec.rb
Having a waterline and a seabed card in the `move-backlog` command was compulsory. Not every team have this two cards, so this should work without them too. :bowtie: 
Fixes https://github.com/openSUSE/trollolo/issues/107.
The error message when one of this cards was not there was not clear, but as this error is not error any more this also closes https://github.com/openSUSE/trollolo/issues/106.
=> Make `move-backlog` to work without waterline

CHANGELOG.md, lib/version.rb
- Add a new `plot-to-board` option to the burndown command to send the plotted
burndown chart to the first card of the `Done` column.
- Add documentation for all CLI commands. Fixes #83.
- Allow to use `move-backlog` without waterline and seabed cards.
Closes #106 and #107.
- Run `burndown` on `cleanup-sprint`. Fixes #68.
=> Prepare version 0.0.13

CHANGELOG.md, lib/version.rb
There was a problem when uploading Trollolo 0.0.13 and repushing doesn't work. From [Rubygems docu](http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem):
> You're not going to run out of gem versions, just push a new one.
=> Prepare version 0.0.14

CHANGELOG.md, lib/burndown_chart.rb
When running `trollolo burndown` with `--plot-to-board` and `-o` options the command failed as it didn't look for the image to upload in the correct directory. :bowtie:
=> Fix burndown --plot-to-board -o

README.md
python 2 packages are now called `python2-*` instead of `python-*`. This change is needed to install the dependencies for plotting the burndown chart.
=> Update README.md to new python naming

CHANGELOG.md, lib/burndown_chart.rb
`trollolo burndown --plot-to-board` only  added the new chart to
the card as an attachment. Trello does not always set the new 
attachment as the cover. This ensures that the attachment is added as a cover.
Fix https://github.com/openSUSE/trollolo/issues/114.
I could not test this code: The tests are broken (failing with current release) 
and I also could not find a test for `trollolo burndown --plot-to-board` to extend.
The change in code is very simple though, just calling one additional "Trello" method.
=> Enforce that plot-to-board sets chart as cover

CHANGELOG.md, lib/burndown_chart.rb, lib/cli.rb, spec/unit/burndown_chart_spec.rb
It should be possible to provide a custom number number for creating a
sprint. As we are currently always updating the sprint with higher
number that also means that we need to be able to modify the sprint for
a concrete Sprint. So, I had implemented a new option `sprint-number`
which can be used for both cases.
Closes https://github.com/openSUSE/trollolo/issues/78
This also contributes to https://github.com/openSUSE/trollolo/issues/76
=> Allow to create an Sprint with a custom number

CHANGELOG.md, lib/version.rb
Changes from 0.0.14:
* Fix `plot-to-board` option in the burndown command when it is used together
with `-o`.
* `burndown --plot-to-board` always sets the burndown chart as the cover.
Fix #114.
* Allow to create and update an Sprint with a custom number. Fix #78.
=> Prepare version 0.1.0

CHANGELOG.md, lib/cli.rb
`burndown-init` does not require `--output` anymore but instead
defaults to the current working directory.
Fix https://github.com/openSUSE/trollolo/issues/103.
=> Add default path to burndown-init

README.md
Currently Trollolo doesn't seem to work with Ruby 2.4.2: https://github.com/openSUSE/trollolo/issues/139
=> Add supported Ruby versions to README

lib/cli.rb, lib/scrum_board.rb, spec/data/vcr/sprint_planning_board.yml, spec/unit/cli_spec.rb
This PR starts to work on #45,
I've created a method on ScrumBoard to get the  Sprint Backlog Column and then on the CLI I created the command and printed the information.
The --velocity option on the #45  is WIP.
=> Add show-backlog command

lib/cli.rb, lib/scrum/sprint_cleaner.rb, lib/settings.rb, spec/unit/scrum/sprint_cleaner_spec.rb
- Adds 'labelled' option in file cli.rb with default value of False
- Adds add_in_last_sprint_label method to add the required label to the moved card if labelled=True
Hey, @Ana06 this is my initial attempt at resolving #138 , What all I figured out: 
- Trollolo uses [thor] (https://github.com/erikhuda/thor/) to manage the cli interface, I added the labelled option to the cleanup_sprint function in cli.rb
- The variable, along with other arguments, is passed to cleanup method located in scrum/sprint_cleaner.rb
- I defined a add_in_last_sprint_label method to perform the addition of label and called it in move_cards if labelled is 'True'
- I referred [ruby-trello]documentation(http://www.rubydoc.info/gems/ruby-trello/Trello/Card#add_label-instance_method) to find out about the add_label …
=> Adds 'in the last sprint' label during cleanup-sprint

lib/cli/scrum.rb, lib/scrum/sprint_cleaner.rb, spec/unit/scrum/sprint_cleaner_spec.rb
In the past `trollolo scrum end-sprint` (formerly `trollolo cleanup-sprint`) generated burndown data every time. Now it requires to be explicitly called with a new flag.
This pull request adds a new flag twhich is named after `trollolo burndown update`:
```
trollolo scrum end-sprint --burndown-update
```
To add this new flag, I first had to fix a problem with `trollolo scrum end-sprint` since it did not pass the boards to `Scrum::SprintCleaner`
Fixes #201 
I could not figure out how to test the cli (what to mock, and how) and opened #203 for now.
=> optional burndown generation on trollolo scrum end-sprint

lib/backup.rb, lib/cli/backup.rb, lib/trollolo.rb, spec/unit/backup_spec.rb, trollolo.gemspec
Hello @Ana06 @cornelius 
On this PR that is a WIP I used [json-diff](https://github.com/espadrine/json-diff)  to diff the backup
from the online version. To do that I created a command on Cli.rb and created a method on Backup.rb to show the backup as json. 
Is this what you were expecting or a custom algorithm of diffing?
After the diff the operations array I need to parse and generate a set of requests to the trello api to do the restore command. Maybe the Diff should be more user friendly and then only use a private version of the diff to the restore command.
Appreciate any suggestions and improvements.
=> Backup Diff: Adding show-diff command (WIP)
